/*
// I'm not sure where the best place for these types to live is
import { DeviceMetadata } from 'src/HomeDevices/ui/ManualAddScreen/types'

// This exists to just be imported by the whitelabel config. This is yet another
// thing that could become server-driven (possibly on the Home feature itself?)
export const OnTechDevices: DeviceMetadata[] = [
  {
    id: '1',
    bestType: 'STREAMING_DONGLE',
    bestMake: 'Google',
    bestModel: 'Chromecast 2018',
    friendlyName: 'Chromecast 3rd Gen',
  },
  {
    id: '2',
    bestType: 'VOICE_CONTROL',
    bestMake: 'Google',
    bestModel: 'Google Home Hub',
    friendlyName: 'Google Home Hub',
  },
  {
    id: '3',
    bestType: 'VOICE_CONTROL',
    bestMake: 'Google',
    bestModel: 'Google Home Mini',
    friendlyName: 'Google Home Mini',
  },
  {
    id: '4',
    bestType: 'ROUTER',
    bestMake: 'Google',
    bestModel: 'Google WiFi',
    friendlyName: 'Google WiFi',
  },
  {
    id: '5',
    bestType: 'SURVEILLANCE_CAMERA',
    bestMake: 'Google',
    bestModel: 'Nest Cam IQ Indoor ',
    friendlyName: 'Nest Cam Indoor',
  },
  {
    id: '6',
    bestType: 'SURVEILLANCE_CAMERA',
    bestMake: 'Google',
    bestModel: 'Nest Cam IQ Outdoor',
    friendlyName: 'Nest Cam Outdoor',
  },
  {
    id: '7',
    bestType: 'SURVEILLANCE_CAMERA',
    bestMake: 'Google',
    bestModel: 'Nest Hello',
    friendlyName: 'Nest Hello',
  },
  {
    id: '8',
    bestType: 'THERMOSTAT',
    bestMake: 'Google',
    bestModel: 'Nest Learning Thermostat',
    friendlyName: 'Nest Thermostat',
  },
  {
    id: '9',
    bestType: 'THERMOSTAT',
    bestMake: 'Google',
    bestModel: 'Nest Temperature Sensor',
    friendlyName: 'Nest Temp Sensor',
  },
  {
    id: '10',
    bestType: 'THERMOSTAT',
    bestMake: 'Google',
    bestModel: 'Nest Thermostat E',
    friendlyName: 'Nest Thermostat E',
  },
  {
    id: '11',
    bestType: 'KEY_LOCK',
    bestMake: 'Google',
    bestModel: 'Nest X Yale Lock',
    friendlyName: 'Nest x Yale Lock',
  },
  {
    id: '12',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Klipsch',
    bestModel: 'RSB14 Sound bar and Wireless Subwoofer',
    friendlyName: 'Klipsch RSB-14',
  },
  {
    id: '13',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Klipsch',
    bestModel: 'The Three',
    friendlyName: 'The Three Spkr',
  },
  {
    id: '14',
    bestType: 'VOICE_CONTROL',
    bestMake: 'Klipsch',
    bestModel: 'The Three with Google Assistant',
    friendlyName: 'The Three Spkr w GA',
  },
  {
    id: '15',
    bestType: 'ROUTER',
    bestMake: 'Linksys',
    bestModel: 'Velop Intelligent Mesh WiFi System Dual Band',
    friendlyName: 'Velop Dual Band WiFi',
  },
  {
    id: '16',
    bestType: 'ROUTER',
    bestMake: 'Linksys',
    bestModel: 'Velop Intelligent Mesh WiFi System Dual-band Plug-in node',
    friendlyName: 'Velop Plug In',
  },
  {
    id: '17',
    bestType: 'ROUTER',
    bestMake: 'Linksys',
    bestModel: 'Velop Intelligent Mesh WiFi System Tri Band',
    friendlyName: 'Velop Tri Band WiFi',
  },
  {
    id: '18',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Polk',
    bestModel: 'MagniFi 5.1 Surround Sound System',
    friendlyName: 'Polk MagniFi 5.1',
  },
  {
    id: '19',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Polk',
    bestModel: 'Smart Bar',
    friendlyName: 'Polk Smart Bar',
  },
  {
    id: '20',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Polk',
    bestModel: 'Smart Bar with Rear Speakers',
    friendlyName: 'Polk Rear',
  },
  {
    id: '21',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Polk',
    bestModel: 'Smart Bar with Subwoofer',
    friendlyName: 'Polk Sub',
  },
  {
    id: '22',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Polk',
    bestModel: 'Sound System with Rear Speakers',
    friendlyName: 'Polk Smart System ',
  },
  {
    id: '23',
    bestType: 'ROUTER',
    bestMake: 'Ring',
    bestModel: 'Chime Pro',
    friendlyName: 'Ring Chime Pro',
  },
  {
    id: '24',
    bestType: 'LIGHT',
    bestMake: 'Ring',
    bestModel: 'Floodlight Cam',
    friendlyName: 'Spotlight Cam',
  },
  {
    id: '25',
    bestType: 'SURVEILLANCE_CAMERA',
    bestMake: 'Ring',
    bestModel: 'Video Doorbell 2',
    friendlyName: 'Ring Doorbell 2',
  },
  {
    id: '26',
    bestType: 'STREAMING_DONGLE',
    bestMake: 'Roku',
    bestModel: '4K Stick Ultra High Definition Media Streamer',
    friendlyName: 'Roku Ultra',
  },
  {
    id: '27',
    bestType: 'STREAMING_DONGLE',
    bestMake: 'Roku',
    bestModel: 'Express HD Media Streamer',
    friendlyName: 'Roku Express',
  },
  {
    id: '28',
    bestType: 'VOICE_CONTROL',
    bestMake: 'Sonos',
    bestModel: 'Sonos One',
    friendlyName: 'Sonos One',
  },
  {
    id: '29',
    bestType: 'SOUND_SYSTEM',
    bestMake: 'Sonos',
    bestModel: 'Sonos Play 5',
    friendlyName: 'Sonos Play 5',
  },
  {
    id: '30',
    bestType: 'SMART_PLUG',
    bestMake: 'Wemo',
    bestModel: 'Mini Smart Plug',
    friendlyName: 'Wemo Mini Plug',
  },
  {
    id: '31',
    bestType: 'SWITCH',
    bestMake: 'Wemo',
    bestModel: 'Insight Switch',
    friendlyName: 'Wemo Switch',
  },
]
/*